@startuml
!unquoted procedure SALT($x)
"{{
salt
%invoke_procedure("_"+$x)
}}" as $x
!endprocedure

!procedure _chooseJ()
{+
**Test Environments**
---
    {/ <b>Joomla | Database | Web Server | PHP }
    {
        {SI
            [] back:lightblue>Joomla 3.8                                        <&blank>
            [X] Joomla 3.9
            [] Joomla 4.0
            [X] Joomla latest
            [] Joomla staging
        }|
        {[<&plus> Add]
        [<&pencil>Edit]
        [<&minus>Remove]}
    }
---
{[ <&x> Cancel ] | [ <&check> Save ]}
}
!endprocedure

!procedure _addJ()
{+
**Joomla**
---
{SI
**Title:**     | "                 "
**Version:**   | ^latest          ^
**Superuser:** | "                 "
**Password:**  | "                 "
}
---
{[ <&x> Cancel ] | [ <&check> Save ]}
}
!endprocedure

!procedure _editJ()
{+
**Joomla**
---
{SI
**Title:**     | "Joomla 3.8       "
**Version:**   | ^3.8             ^
**Superuser:** | "admin            "
**Password:**  | "admin            "
}
---
{[ <&x> Cancel ] | [ <&check> Save ]}
}
!endprocedure

!procedure _chooseD()
{+
**Test Environments**
---
    {/ Joomla | <b>Database | Web Server | PHP }
    {
        {SI
            [] MySQL
            [X] MariaDB
            [X] <back:lightblue>PostGreSQL                                      <&blank>
            [] MS SQL Server
            <&blank>
        }|
        {[<&plus> Add]
        [<&pencil>Edit]
        [<&minus>Remove]}
    }
---
{[ <&x> Cancel ] | [ <&check> Save ]}
}
!endprocedure

!procedure _addD()
{+
**Database**
---
{SI
**Title:**     | "                 "
**Database:**  | ^MySQL           ^
**Version:**   | ^latest          ^
**User:**      | "                 "
}
---
{[ <&x> Cancel ] | [ <&check> Save ]}
}
!endprocedure

!procedure _editD()
{+
**Database**
---
{SI
**Title:**     | "PostGreSQL       "
**Database:**  | ^PostGreSQL      ^
**Version:**   | ^latest          ^
**User:**      | "sqladmin         "
}
---
{[ <&x> Cancel ] | [ <&check> Save ]}
}
!endprocedure

!procedure _chooseW()
{+
**Test Environments**
---
    {/ Joomla | Database | <b>Web Server | PHP }
    {
        {SI
            [X] Apache2 w/ mod_php
            [X] Apache2 w/ PHP-FPM
            [X] back:lightblue>NginX                                                 <&blank>
            [] LigHTTPd
            <&blank>
        }|
        {[<&plus> Add]
        [<&pencil>Edit]
        [<&minus>Remove]}
    }
---
{[ <&x> Cancel ] | [ <&check> Save ]}
}
!endprocedure

!procedure _addW()
{+
**Web Server**
---
{SI
**Title:**     | "                 "
**Server:**    | ^Apache2+mod_php ^
**Version:**   | ^latest          ^
<&blank>
}
---
{[ <&x> Cancel ] | [ <&check> Save ]}
}
!endprocedure

!procedure _editW()
{+
**Web Server**
---
{SI
**Title:**     | "NginX            "
**Server:**    | ^NginX           ^
**Version:**   | ^1.9             ^
<&blank>
}
---
{[ <&x> Cancel ] | [ <&check> Save ]}
}
!endprocedure

!procedure _chooseP()
{+
**Test Environments**
---
    {/ Joomla | Database | Web Server | <b>PHP }
    {
        {SI
            [X] PHP 7.2
            [X] PHP 7.3
            [X] PHP 7.4
            [X] PHP 8.0
            [X] <back:lightblue>PHP latest                                        <&blank>
        }|
        {[<&plus> Add]
        [<&pencil>Edit]
        [<&minus>Remove]}
    }
---
{[ <&x> Cancel ] | [ <&check> Save ]}
}
!endprocedure

!procedure _addP()
{+
**PHP**
---
{SI
**Title:**     | "                 "
**Version:**   | ^latest          ^
<&blank>
<&blank>
}
---
{[ <&x> Cancel ] | [ <&check> Save ]}
}
!endprocedure

!procedure _editP()
{+
**PHP**
---
{SI
**Title:**     | "PHP latest        "
**Version:**   | ^latest           ^
<&blank>
<&blank>
}
---
{[ <&x> Cancel ] | [ <&check> Save ]}
}
!endprocedure

(*) --> SALT(chooseJ)
-> [Remove] chooseJ
--> [Add] SALT(addJ)
-> [Cancel/Save] chooseJ
--> [Edit] SALT(editJ)
-> [Cancel/Save] chooseJ
---> [Cancel/Save] (*)
(*) --> SALT(chooseD)
-> [Remove] chooseD
--> [Add] SALT(addD)
-> [Cancel/Save] chooseD
--> [Edit] SALT(editD)
-> [Cancel/Save] chooseD
---> [Cancel/Save] (*)
(*) --> SALT(chooseW)
--> [Remove] chooseW
--> [Add] SALT(addW)
-> [Cancel/Save] chooseW
--> [Edit] SALT(editW)
-> [Cancel/Save] chooseW
---> [Cancel/Save] (*)
(*) --> SALT(chooseP)
-> [Remove] chooseP
--> [Add] SALT(addP)
-> [Cancel/Save] chooseP
--> [Edit] SALT(editP)
-> [Cancel/Save] chooseP
---> [Cancel/Save] (*)
@enduml
